
server:
  port: 1000

spring:
  application:
    name: EUREKA-SERVER #服务名称
  security:
    user:
      name: user
      password: 123456
eureka:
  client:
    register-with-eureka: false #flase禁止注册自身
    fetch-registry: false
    #因为该服务没有注册到其他注册中心，所以关闭从注册中心拉取服务列表。
    #如果是服务注册中心集群，需要开启，开启就是去掉该配置，采用默认配置即可
    service-url:
      defaultZone: http://user:123456@localhost:${server.port}//eureka/ #服务注册中心地址，http://账号:密码@主机名称:端口/Eureka
#    server:
#      renewalPercentThreshold: 0.49 #设置心跳正常的阀值，默认为1，测试时可以调低
#      enableSelfPreservation: true # 开启自我保护
#      evictionIntervalTimerInMs: 10000 #清理无效节点时间间隔
