
server:
  port: 1101
spring:
  application:
    name: USER-PROVIDER
  datasource:
    username: timtest
    password: test123#
    url: jdbc:mysql://gz-cdb-rgl276ny.sql.tencentcdb.com:62592/tim_chat?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:1000/eureka/      #服务注册中心地址，含有BASIC认证的用户名和密码
#      defaultZone: http://user:123456@106.14.135.154:1000/eureka/      #服务注册中心地址，含有BASIC认证的用户名和密码
  instance:
    prefer-ip-address: true  #将IP注册到服务注册中心

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  #    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
  typeAliasesPackage: com.yiung.api.entity
#  mapper配置
#mapper:
#  mappers: tk.common.mapper.BasicMapper
#  identity: MYSQL
###  mybatis 分页插件使用
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

# 打印sql
logging:
  level:
    com.yiung : debug

#放开所有节点
#management:
#  endpoint:
#    web:
#      exposure:
#        include: '*'