server:
  port: 1201
spring:
  application:
    name: WORKBENCH-SERVICE
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: always
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:1000/eureka/      #服务注册中信地址，含有BASIC认证的用户名和密码
  instance:
    prefer-ip-address: true  #将IP注册到服务注册中心

feign:
  compression:
    request:
      enabled: true

#放开所有节点
#management:
#  endpoint:
#    web:
#      exposure:
#        include: '*'